name: Docs

on:
  push:
    branches: ["master", "main"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs-requirements.txt
      - name: Build docs
        run: mkdocs build --strict
      - name: Deploy docs
        run: mkdocs gh-deploy --force --strict
